package io.github.amayaframework.core;

import io.github.amayaframework.core.controllers.Controller;
import io.github.amayaframework.core.handlers.PipelineHandler;
import io.github.amayaframework.server.interfaces.HttpContext;

import java.net.InetSocketAddress;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.function.Consumer;

/**
 * The interface representing the main entity of the framework - server.
 */
public interface AmayaServer {
    /**
     * Starts server.
     */
    void start();

    /**
     * Stops the server with a delay.
     *
     * @param delay required delay
     */
    void stop(int delay);

    /**
     * Stops the server immediately.
     */
    void stop();

    /**
     * Returns the {@link Executor} used by the server
     *
     * @return {@link Executor}
     */
    Executor getExecutor();

    /**
     * Adds the controller, executing all pipeline configurators on it before that.
     *
     * @param controller {@link Controller} the path of which must not be null
     * @return {@link HttpContext} generated by sun server
     */
    HttpContext addController(Controller controller);

    /**
     * Sets a list of configurators that will be used when adding each controller.
     *
     * @param configurators {@link List} configurators to be set. Must be not null.
     */
    void setPipelineConfigurators(List<Consumer<PipelineHandler>> configurators);

    /**
     * Returns the address to which the server is bound
     *
     * @return {@link InetSocketAddress}
     */
    InetSocketAddress getAddress();
}
